# Generated by Django 3.1.5 on 2021-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='you Forgot Me!', max_length=200),
            preserve_default=False,
        ),
    ]
